config/routes.rb
Nubemovie::Application.routes.draw do

  
  resources :search, only: [:new, :create]

  root :to =>            'search#new'

  match '/result',   to: 'static_pages#result'
 
  match '/search',   to: 'search#search'

  match '/torrent',  to: 'search#torrent'

  match '/list',     to: 'search#list'

end

app/models/search.rb
class Search
  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :query, :typeList

  def initialize(attributes = {})
  	attributes.each do |name, value|
  		send("#{name}=", value)
  	end
  end

  def persisted?
  	false
  end

  def movies=(movies)
  	@movies = movies
  end

  def movies()
  	@movies
  end

  def torrents=(torrents)
  	@torrents = torrents
  end

  def torrents()
  	@torrents
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery

end

app/controllers/search_controller.rb
class SearchController < ApplicationController

  def new

  end

  def create
  	@search = Search.new(params[:search])
  	bf = BadFruit.new('q5kk3jg9um8qt9sukxnv9yet')
  	if @search.valid?      
      if !@search.query.blank?
        @search.movies = bf.movies.search_by_name(@search.query,20)
        render action: 'search'
  		else
  			redirect_to '/' 
  		end
    else
      redirect_to '/'
    end
  end
  
  def search

  end

  def torrent
  	@search = Search.new()
  	@search.torrents = JSON.parse(HTTParty.get('http://isohunt.com/js/json.php?' + { ihq: params[:search], rows: 20 }.to_query))['items']['list']
  	render action: 'torrent'
  end	

  def list
    bf = BadFruit.new('q5kk3jg9um8qt9sukxnv9yet')
    @search = Search.new()
    @search.movies = bf.lists.send(params[:typeMethod]) if bf.lists.respond_to? params[:typeMethod]
    @search.typeList = params[:typeList]
    render action: 'list'
  end    

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    nubeMOVIE
    by Pedro Marce Rodriguez
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
       <%= link_to "nubeMOVIE", '/', id: "logo" %>
       <nav>
         <ul class="nav pull-right">
          <li><%= link_to "Home",  '/' %></li>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>nubeMOVIE</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">        
    <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

app/views/search/list.html.erb
<h2><%= @search.typeList %></h2>

<div class="row">
		<table class="center table">
		  <tr>
		    <th>&nbsp</th>
		    <th>Movie</th>
		    <th>Year</th>
		    <th>Critics</th>
		    <th>Audience</th>
		  </tr>

		<% @search.movies.each do |movie| %>
		  <tr>
		  	<td> <%= image_tag movie.posters.thumbnail %> </td>
		    <td><p><%= link_to movie.name, '/torrent?' + { search: movie.name + ' ' + movie.year.to_s }.to_query %></p></td>
		    <td><p><%= movie.year %></p></td>
		    <td><p><%= movie.scores.critics_score %></p></td>
		    <td><p><%= movie.scores.audience_score %></p></td>
		  </tr>
		<% end %>
		</table>  
</div>

app/views/search/new.html.erb
<h2>Movies</h2>

<div class="row">

	<div class="span3">
    <ul>
      <li class="btn btn-mini btn-block">
        <%= link_to 'In Theaters', '/list?' + { typeMethod: 'in_theaters', typeList: 'In Theaters' }.to_query %>
      </li>
      <li class="btn btn-mini btn-block">
        <%= link_to 'Opening Movies', '/list?' + { typeMethod: 'opening_movies', typeList: 'Opening Movies' }.to_query %>
      </li>
      <li class="btn btn-mini btn-block">
        <%= link_to 'New DVD releases', '/list?' + { typeMethod: 'new_dvd_releases', typeList: 'New DVD releases' }.to_query %>
      </li>
      <li class="btn btn-mini btn-block">
        <%= link_to 'Curent DVD releases', '/list?' + { typeMethod: 'current_dvd_releases', typeList: 'Curent DVD releases' }.to_query %>
      </li>
    </ul>
  </div>
  <div class="center span6">

  	<%= form_for(:search, url: search_path) do |f| %>

      <%= f.text_field :query %>

      <%= f.submit "Search", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/search/search.html.erb
<h2>Results</h2>

<div class="row">
		<table class="center table">
		  <tr>
		    <th>&nbsp</th>
		    <th>Movie</th>
		    <th>Year</th>
		    <th>Critics</th>
		    <th>Audience</th>
		  </tr>

		<% @search.movies.each do |movie| %>
		  <tr>
		  	<td> <%= image_tag movie.posters.thumbnail %> </td>
		    <td><p><%= link_to movie.name, '/torrent?' + { search: movie.name + ' ' + movie.year.to_s }.to_query %></p></td>
		    <td><p><%= movie.year %></p></td>
		    <td><p><%= movie.scores.critics_score %></p></td>
		    <td><p><%= movie.scores.audience_score %></p></td>
		  </tr>
		<% end %>
		</table>  
</div>
    

app/views/search/torrent.html.erb
<h2>Torrents</h2>

<div class="row">
  	<table class="table">
		  <tr>
		    <th>File</th>
		    <th>Size</th>
		    <th>Seeds</th>
		    <th>Lechers</th>
		    <th>&nbsp</th>
		  </tr>

		<% @search.torrents.each do |torrent| %>
		  <tr>
		  	<td> <%= raw torrent['title'] %> </td>
		    <td><p><%= torrent['size'] %></p></td>
		    <td><p><%= torrent['Seeds'] %></p></td>
		    <td><p><%= torrent['leechers'] %></p></td>
		    <td><p><%= link_to 'Download', torrent['enclosure_url'] %></p></td>
		  </tr>
		<% end %>
		</table>  
           

</div>

app/views/static_pages/result.html.erb
<h1>Results</h1>

<div class="row">
  <div class="span6 offset3">

         <%= @search.movies.count %>

  </div>
</div>
    